apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mysql
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    {{- .Values.spec.destination | toYaml | nindent 4 }}
  project: default
  source:
    helm:
      valueFiles:
      - values.yaml
    path: mysql
    repoURL: {{ .Values.spec.source.repoURL }}
    targetRevision: HEAD
  syncPolicy:
    {{- .Values.spec.syncPolicy | toYaml | nindent 4 }}
